### ISSUE TITLE
Error in beforeCreate hook: "Error: Vuetify is not properly initialized,

### ISSUE THREAD

**Issue by realakuma** [michoelchaikin/netsuite-mapreduce-util#1]
Hi bro

Sorry to disturb you. I have deployed codes to netsuite and when I opened the suitelet. The following errors occurred:
Error in beforeCreate hook: "Error: Vuetify is not properly initialized, see 

Best Regards

Bin

**Comment by realakuma** [comment]
Hi Bro
After adding vuetify: new Vuetify() in the script.js. Everything is perfect! 
Thanks.
Bin

**Comment by michoelchaikin** [comment]
Hey Bin,

Apologies for the delayed response. This issue was due to me including Vuetify from a CDN without specifying the version which means that when Veutify 2 was released with breaking changes it automatically updated. I've just committed some significant changes to the build system using [create-spa-netsuite](https://www.npmjs.com/package/@finitydevs/create-spa-netsuite) that amongst everything else resolves this issue.

Regards,

Michoel
